apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: api
#  clusterIP: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
#  replicas: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
#          image: dockersamples/wordsmith-api
          image: me-west1-docker.pkg.dev/akiva-ashkenazi/docker-repo/api:latest
          ports:
            - containerPort: 8080
              name: api
          resources:
            requests:
              cpu: "100m"     # Set realistic resource requests
              memory: "128Mi"
            limits:
              cpu: "500m"     # Set realistic resource limits
              memory: "512Mi"